---
name: 💖 申请加入案例
description: 申请将你的站点展示在文档站案例页
title: 申请加入案例
labels: join case
body:
  - type: markdown
    attributes:
      value: |
        感谢您抽出宝贵时间填写这份申请加入案例表单！
  - type: textarea
    attributes:
      label: 模板
      description: |
          - 名称: 站点名称
          - 简介: 站点简介
          - 链接: 站点链接
          - 截图: 站点截图链接
          - 作者: 作者名称
          - 头像: 作者头像链接
          - 备注(可选，只能选择一个填写): 知识库兼博客 | 社区 | 知识库 | 博客 | 文档站
      value: |
          - 名称: 
          - 简介: 
          - 链接: 
          - 截图: 
          - 作者: 
          - 头像: 
          - 备注: 
      render: markdown
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 确认项
      description: 提交表单之前，请确保您已满足以下确认项
      options:
        - label: 使用 Teek 主题
          required: true
        - label: 有 10 篇以上文章
          required: true
        - label: 保留 Footer 的主题版本（点击可以跳转主题链接）
          required: true
---

名称: 站点名称
简介: 站点简介
链接: 站点链接
截图: 站点截图链接
作者: 作者名称
头像: 作者头像链接

备注(可选，只能选择一个填写)： 知识库兼博客 | 社区 | 知识库 | 博客 | 文档站
